apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hpa-demo
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra-structure
  source:
    repoURL: https://github.com/hosytt/k8s-operations.git
    path: infra/hpa-demo
    targetRevision: main
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
