apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nestjs-app
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra-structure
  source:
    repoURL: https://github.com/hosytt/k8s-operations.git
    path: app/gitops
    targetRevision: main
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: nestjs-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
